M48
; DRILL file {KiCad 9.0.3} date 2025-11-25T14:27:02-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-25T14:27:02-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X42.33Y-48.6
T2
X43.5Y-61.703
X50.5Y-61.703
X120.61Y-47.797
X127.61Y-47.797
T3
X46.83Y-48.6
T4
X41.227Y-39.397
X41.227Y-83.44
X129.952Y-39.397
X129.952Y-83.44
M30
